language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - ANDROID_API=android-24            # API-version für den Emulator (android-XX)
    - ANDROID_ABI=arm64-v8a             # das Image für den Emulator (armv7/armv8/x86/x86_64)
    - ANDROID_BUILD_TOOLS=26.0.2        # die Version der build-tools (am besten aktuellste version)
    - ADB_INSTALL_TIMEOUT=5             # Timeout für die Installation der App im Emulator
android:
  components:
    #- tools                            # SDK-update
    - platform-tools                    # platform-tools update
    - tools                             # SDK-update
    - build-tools-$ANDROID_BUILD_TOOLS  # build-tools, welche die App verwendet
    - android-$ANDROID_API              # Android SDK um die App zu kompilieren
    - extra-android-m2repository        # evt. benötigte m2-repositories
    - $ANDROID_ABI-$ANDROID_API

# Emulator Management: erzeugen, starten und warten
before_script:
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager --update
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "system-images;$ANDROID_API;default;$ANDROID_ABI"
  - echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n test  -k "system-images;$ANDROID_API;default;$ANDROID_ABI"
  - $ANDROID_HOME/tools/emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - sonar-scanner

addons:
  sonarcloud:
    organization: "winchester-games" # der key der organisation auf sonarcloud.io
    token:
      secure: $SONAR_TOKEN       # $SONAR_TOKEN -> Umgebungsvariable auf travis-ci.org

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

# benachrichtigungen per email auszuschalten
#notifications:
#  email: false
